baseURL = 'https://www.terrapeneornata.com'
languageCode = 'en-us'
title = 'Terrapene Ornata'
theme = 'paper'

[params]
# social icons
bluesky = 'mikegruz.bsky.social'
mastodon = 'https://mstdn.social/@mikegruz'
rss = true

# home page
name = 'Mike Gruszczynski'
bio = 'Academic, Birder, Native Plant Enthusiast, Experimental Music Dabbler'

monoDarkIcon = true